### PR TITLE
Combined all JS Files in libs dir except chart.min.js, added async de…

### PR DESCRIPTION
**Pull request by adamseoul**
"Combined all JS Files in libs dir except chart.min.js, added async defer to loading tags

### CODE REVIEW

**Comment by JTuwiner** [comment]
Okay, I made this changes: 

https://github.com/BuyBitcoinWorldwide/buybitcoinworldwide.github.io/commit/bce216fad96a0337d364734a2b7312ff83c8ce1b
https://github.com/BuyBitcoinWorldwide/buybitcoinworldwide.github.io/commit/b849e3805a7e1a95e7382bfc1dd92d2380a5ebed

**Comment by adamseoul** [comment]
great, there is a new file in there a chart,js, its at the top so I am thinking someone put it at the top for a reason.
will need to inline the js from the file if it still comes up on pagespeed.

My HTML version here is ok https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.webconcepts.com.au%2Fsites%2Fbitcoins%2Fwww.buybitcoinworldwide.com%2Findex-now.html

**Comment by JTuwiner** [comment]
I had to revert since something was messing up the select2 JS (that allows people to search countries on the home page). Can you make one new pull request based on current state of repo?

**Comment by JTuwiner** [comment]
You can see in your screenshot on the page speed test the country and payment method boxes are off center, there is some issue with the select2 js

**Comment by adamseoul** [comment]
Hi will make a reverse proxy on my server so that I can use pagespeed. Was only modifying my captured HTML file up until today.

**Comment by JTuwiner** [comment]
Let's just fix this error: 

Optimize CSS Delivery of the following:

    https://www.buybitcoinworldwide.com/stylesheets/shiori.css

Other JS errors not as crucial now since they only affect home page. Error above affects all pages.

**Comment by adamseoul** [comment]
yep ok, send it over asap

**Pull request closed without merging**
