### PR TITLE
Adding remitano

### PR DESCRIPTION
**Pull request by phuongnd08**

### CODE REVIEW

**Comment by phuongnd08** [comment]
I'm trying to add our site remitano.com. Still do not sure why it is not getting listed when we test on our github pages. Visiting /exchanges/remitano/ render 404. Visting /exchange/remitano (without the final slash) render a page without css. Could you give some advice?

**Comment by JTuwiner** [comment]
Hey, thanks for submitting your exchange. Try again but only edit necessary parts of https://github.com/BuyBitcoinWorldwide/buybitcoinworldwide.github.io/blob/master/_data/buy.yml

**Comment by phuongnd08** [comment]
Right, I don't consider this pull request is ready yet. Just trying to understand why it not working yet.

**Comment by JTuwiner** [comment]
It will work. If it doesn't I will manually add your data. Feel free to re-submit whenever!

**Comment by phuongnd08** [comment]
I hosted it here: https://phuongnd08.github.io
When I navigate to https://phuongnd08.github.io/exchanges/remitano/ it renders error page.
What is missing?

**Comment by JTuwiner** [comment]
I'm not sure, anyway I can't add a review for this exchange now so if you want it added then try submitting just buy.yml data.

**Comment by phuongnd08** [comment]
Okay, so I submitted another pull request here: https://github.com/BuyBitcoinWorldwide/buybitcoinworldwide.github.io/pull/25

**Pull request closed without merging**
